### ISSUE TITLE
Stopped polling job due to exception: System.MissingMethodException: UnityEditor.VersionControl.Task

### ISSUE THREAD

**Issue by Bibzball** [googlesamples/unity-jar-resolver#262]
I updated Play Services Resolver to v1.2.123 and am getting this error on every auto-resolve.
Using Unity 2019.1.11f1

> `Stopped polling job due to exception: System.MissingMethodException: UnityEditor.VersionControl.Task UnityEditor.VersionControl.Provider.Checkout(string,UnityEditor.VersionControl.CheckoutMode)
>   at Google.ProjectSettings.Set[T] (System.String name, T value) [0x00024] in /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/ProjectSettings.cs:119 
>   at Google.ProjectSettings+<SetBool>c__AnonStorey2.<>m__5 () [0x00000] in /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/ProjectSettings.cs:154 
>   at Google.ProjectSettings.SavePreferences (Google.ProjectSettings+SettingsSave saveLevel, System.Action saveToProject, System.Action saveToEditor) [0x00035] in /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/ProjectSettings.cs:135 
>   at Google.ProjectSettings.SetBool (System.String name, System.Boolean value) [0x00014] in /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/ProjectSettings.cs:153 
>   at GooglePlayServices.SettingsDialog.set_UseJetifier (System.Boolean value) [0x00000] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/SettingsDialog.cs:225 
>   at GooglePlayServices.PlayServicesResolver.CanEnableJetifierOrPromptUser (System.String titlePrefix) [0x00179] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:2270 
>   at GooglePlayServices.PlayServicesResolver.ResolveUnsafe (System.Action`1[T] resolutionComplete, System.Boolean forceResolution, System.Boolean isAutoResolveJob, System.Boolean closeWindowOnCompletion) [0x00012] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1610 
>   at GooglePlayServices.PlayServicesResolver+<ScheduleResolve>c__AnonStorey1E.<>m__40 () [0x00000] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1579 
>   at GooglePlayServices.PlayServicesResolver.ExecuteNextResolveJob () [0x00069] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1438 
>   at GooglePlayServices.PlayServicesResolver.ScheduleResolve (System.Boolean forceResolution, System.Boolean closeWindowOnCompletion, System.Action`1[T] resolutionCompleteWithResult, System.Boolean isAutoResolveJob) [0x000a7] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1592 
>   at GooglePlayServices.PlayServicesResolver.AutoResolve (System.Action resolutionComplete) [0x00017] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1113 
>   at GooglePlayServices.PlayServicesResolver.<ScheduleAutoResolve>m__48 () [0x00016] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1092 
>   at Google.RunOnMainThread.ExecutePollingJobs () [0x0004a] in /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:300 
> UnityEngine.Debug:LogError(Object)
> Google.RunOnMainThread:ExecutePollingJobs() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:303)
> Google.RunOnMainThread:<ExecuteAll>m__17() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:414)
> Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
> Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
> UnityEditor.EditorApplication:Internal_CallUpdateFunctions()`

**Comment by stewartmiles** [comment]
Thanks for the report, looks like a regression due to https://github.com/googlesamples/unity-jar-resolver/pull/256 and Unity - likely - have changed this API.  @JimmyDeemo FYI

**Comment by JimmyDeemo** [comment]
Roger that. I’ll try in Unity 2019 and see if I can come up with a fix.

**Comment by JimmyDeemo** [comment]
@Bibzball Please can you tell me what .NET version your project is using?

**Comment by Bibzball** [comment]
@JimmyDeemo It's setup as ".NET 4.x Equivalent"

**Comment by supersolid-Justy** [comment]
I see references of the 3.5 framework in the resolver which is deprecated in Unity 2019.1, so maybe theres something in this direction?

**Comment by JimmyDeemo** [comment]
Please can you tell me how would I make sure that compilation is using the higher runtime, given this plugin is compiled to a .dll? How can I support Unity 2017/2018 that have both runtimes as well as 2019 that only has the higher one?

**Comment by Bibzball** [comment]
@JimmyDeemo Not sure if I'm understanding your issue correctly, but maybe I can help? I'm also developing Unity plugins currently.
Since I can't use #if UNITY_XXXX_OR_NEWER, I created a UnityVersionAtLeast(string version) helper that parse Application.unityVersion (which returns "201X.Y.ZZf1") to compare unity versions and allow you to call UnityVersionAtLeast("2019.1.1") to call different methods depending on Unity Version.

Sorry if I'm accidentally completely off-topic!

**Comment by stewartmiles** [comment]
Folks, the resolver needs to be compiled against .NET 3.x since it works all the way back to Unity 4.7 (yes some folks still ship profitable games with Unity 4.x).

I think for the moment I'm going to bandaid this by wrapping the logic in try / catch just so the regression is fixed.

At runtime we already have code that will get the Unity version https://github.com/googlesamples/unity-jar-resolver/blob/ecfc41a15f4be10e8b3c88aca4352c4c17e38a3e/source/VersionHandlerImpl/src/ExecutionEnvironment.cs#L48 however doing things conditional based upon this is so crazy brittle.  It's better to just try to access a method / property / field using reflection, catch the exception and fallback for different versions as Unity tend to backport fixes which breaks simply version checking.

**Comment by stewartmiles** [comment]
Oh I see @JimmyDeemo has a patch in https://github.com/googlesamples/unity-jar-resolver/pull/263, well lets give that a whirl.

**Comment by JimmyDeemo** [comment]
Very sorry @stewartmiles but that patch doesn’t actually address the Unity version issue. I haven’t had chance to get a project setup that uses Perforce and Unity 2019.

Tbh I’m still a little hazy on why the call is a problem; the API hasn’t changed.

**Comment by stewartmiles** [comment]
I took a look at the old and new API signatures and they have changed

`public static Task Checkout(string asset, CheckoutMode mode)`

changed to..

`public static Task Checkout(string asset, CheckoutMode mode, ChangeSet changeset = null)`

The problem is that the compiler bakes out the additional arguments required for methods in the calling module, so calling Checkout(asset, mode) and compiling the DLL with Unity 2019's DLL will result in Checkout(asset, mode, changeset) in the IL. 

See https://haacked.com/archive/2010/08/10/versioning-issues-with-optional-arguments.aspx/

I'll use reflection to workaround this.

**Comment by stewartmiles** [comment]
Fixed in https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.124

**Comment by supersolid-Justy** [comment]
Also it is currently being worked on by Unity:
https://issuetracker.unity3d.com/issues/vcs-addition-of-changeset-changeset-equals-null-argument-to-provider-dot-checkout-broke-prebuilt-assemblies-in-2019-dot-1-plus

**Comment by aras-p** [comment]
Yeah turns out we accidentally broke this API when used from precompiled assemblies in 2019.x. Sorry about that, fixing it now!

**Comment by aras-p** [comment]
FYI fix for that on Unity side should be in Unity 2019.2.5f1 soon (already fixed in 2019.3).

**Comment by hesham-akmal** [comment]
I'm getting this on Unity 2018.4.7f1 with unity-jar-resolver v1.2.124.

Stopped polling job due to exception: System.NullReferenceException: Object reference not set to an instance of an object
  at GooglePlayServices.UnityCompat.VersionFromAndroidSDKVersionsEnum (System.String enumName, System.String fallbackPrefKey, System.Int32 fallbackValue) [0x00000] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/UnityCompat.cs:66 
  at GooglePlayServices.UnityCompat.GetAndroidTargetSDKVersion () [0x00015] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/UnityCompat.cs:115 
  at GooglePlayServices.PlayServicesResolver.CanEnableJetifierOrPromptUser (System.String titlePrefix) [0x000ae] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:2236 
  at GooglePlayServices.PlayServicesResolver.ResolveUnsafe (System.Action`1[T] resolutionComplete, System.Boolean forceResolution, System.Boolean isAutoResolveJob, System.Boolean closeWindowOnCompletion) [0x00012] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1617 
  at GooglePlayServices.PlayServicesResolver+<ScheduleResolve>c__AnonStorey1E.<>m__40 () [0x00000] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1586 
  at GooglePlayServices.PlayServicesResolver.ExecuteNextResolveJob () [0x00069] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1445 
  at GooglePlayServices.PlayServicesResolver.ScheduleResolve (System.Boolean forceResolution, System.Boolean closeWindowOnCompletion, System.Action`1[T] resolutionCompleteWithResult, System.Boolean isAutoResolveJob) [0x000a7] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1599 
  at GooglePlayServices.PlayServicesResolver.AutoResolve (System.Action resolutionComplete) [0x00017] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1120 
  at GooglePlayServices.PlayServicesResolver.<ScheduleAutoResolve>m__48 () [0x00016] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1099 
  at Google.RunOnMainThread.ExecutePollingJobs () [0x0004a] in /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:300 
UnityEngine.Debug:LogError(Object)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:303)
Google.RunOnMainThread:<ExecuteAll>m__17() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:414)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)

**Comment by criistii** [comment]
I am getting the same error as @hesham-akmal 
Still not sure how to fix it.
Using Unity 2019.2.5f1 with Facebook and Firebase for Unity.
Firebase is the last installed, so I am working with version v1.2.124.0 of Play ServicesResolver

**Comment by hesham-akmal** [comment]
> I am getting the same error as @hesham-akmal
> Still not sure how to fix it.
> Using Unity 2019.2.5f1 with Facebook and Firebase for Unity.
> Firebase is the last installed, so I am working with version v1.2.124.0 of Play ServicesResolver

I'm not sure how I've fixed this, but these were the things I've done:
-Deleting library folder, try deleting everything actually except Assets, Packages, and ProjectSettings.
-Delete play services resolver completely
-Switch platform to anything else then to android
-Import resolver again and try?

**Comment by criistii** [comment]
Sadly, this did not work. I am stuck and unable to get my solution to compile.

In case this helps:

> Stopped polling job due to exception: System.NullReferenceException: Object reference not set to an instance of an object
  at GooglePlayServices.UnityCompat.VersionFromAndroidSDKVersionsEnum (System.String enumName, System.String fallbackPrefKey, System.Int32 fallbackValue) [0x00000] in Z:\tmp\tmp.nVTUgeIjTw\third_party\unity\unity_jar_resolver\source\PlayServicesResolver\src\UnityCompat.cs:66 
  at GooglePlayServices.UnityCompat.GetAndroidTargetSDKVersion () [0x00015] in Z:\tmp\tmp.nVTUgeIjTw\third_party\unity\unity_jar_resolver\source\PlayServicesResolver\src\UnityCompat.cs:115 
  at GooglePlayServices.PlayServicesResolver.CanEnableJetifierOrPromptUser (System.String titlePrefix) [0x000ae] in Z:\tmp\tmp.nVTUgeIjTw\third_party\unity\unity_jar_resolver\source\PlayServicesResolver\src\PlayServicesResolver.cs:2236 
  at GooglePlayServices.PlayServicesResolver.ResolveUnsafe (System.Action`1[T] resolutionComplete, System.Boolean forceResolution, System.Boolean isAutoResolveJob, System.Boolean closeWindowOnCompletion) [0x00012] in Z:\tmp\tmp.nVTUgeIjTw\third_party\unity\unity_jar_resolver\source\PlayServicesResolver\src\PlayServicesResolver.cs:1617 
  at GooglePlayServices.PlayServicesResolver+<ScheduleResolve>c__AnonStorey5.<>m__0 () [0x00000] in Z:\tmp\tmp.nVTUgeIjTw\third_party\unity\unity_jar_resolver\source\PlayServicesResolver\src\PlayServicesResolver.cs:1586 
  at GooglePlayServices.PlayServicesResolver.ExecuteNextResolveJob () [0x00069] in Z:\tmp\tmp.nVTUgeIjTw\third_party\unity\unity_jar_resolver\source\PlayServicesResolver\src\PlayServicesResolver.cs:1445 
  at GooglePlayServices.PlayServicesResolver.ScheduleResolve (System.Boolean forceResolution, System.Boolean closeWindowOnCompletion, System.Action`1[T] resolutionCompleteWithResult, System.Boolean isAutoResolveJob) [0x000a7] in Z:\tmp\tmp.nVTUgeIjTw\third_party\unity\unity_jar_resolver\source\PlayServicesResolver\src\PlayServicesResolver.cs:1599 
  at GooglePlayServices.PlayServicesResolver.AutoResolve (System.Action resolutionComplete) [0x00017] in Z:\tmp\tmp.nVTUgeIjTw\third_party\unity\unity_jar_resolver\source\PlayServicesResolver\src\PlayServicesResolver.cs:1120 
  at GooglePlayServices.PlayServicesResolver.<ScheduleAutoResolve>m__8 () [0x00016] in Z:\tmp\tmp.nVTUgeIjTw\third_party\unity\unity_jar_resolver\source\PlayServicesResolver\src\PlayServicesResolver.cs:1099 
  at Google.RunOnMainThread.ExecutePollingJobs () [0x0004a] in Z:\tmp\tmp.V9Sj4RiRb9\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:300 
UnityEngine.Debug:LogError(Object)
Google.RunOnMainThread:ExecutePollingJobs() (at Z:/tmp/tmp.V9Sj4RiRb9/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:303)
Google.RunOnMainThread:<ExecuteAll>m__1() (at Z:/tmp/tmp.V9Sj4RiRb9/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:414)
Google.RunOnMainThread:RunAction(Action) (at Z:/tmp/tmp.V9Sj4RiRb9/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at Z:/tmp/tmp.V9Sj4RiRb9/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by hesham-akmal** [comment]
Okay one more thing I forgot to mention, the project target sdk was android Q preview or something like that, try changing that to 19?

**Comment by criistii** [comment]
THANK YOU! Yes, this was the problem, I switched from Android 29 to 28 and it worked again!
