### ISSUE TITLE
Resolved aars-files differ on Windows and Macos

### ISSUE THREAD

**Issue by oriontvv** [googlesamples/unity-jar-resolver#279]
I'm using `Unity 2019.1.14f1, Play Services Resolver 1.2.124` and git on Windows and MacOS.

Some `*.aar` files (for example firebase-unity) and `ProjectSettings/AndroidResolverDependencies.xml`(for example    `<setting name="packageDir" value="Assets/Plugins/Android" /> `) contains different slash symbols for different operation systems so I can't commit or ignore them because It'll be impossible to build apk without the files.

Upgrading Play Services Resolver to 1.2.125 doesn't change anything. What should I do?

**Comment by stewartmiles** [comment]
@oriontvv I don't understand why the slash in file paths stored in the `AndroidResolverDependencies.xml` makes a difference here.  What is going wrong exactly?

**Comment by oriontvv** [comment]
Actually I don't understand why slashes change but I see such git diff on macos after I resolve dependencies (on build apk). Maybe it's default path for android plugins in unity.
``` diff
-    <setting name="packageDir" value="Assets\Plugins\Android" />
+    <setting name="packageDir" value="Assets/Plugins/Android" />
```

**Comment by stewartmiles** [comment]
Ah, that would change when resolution occurs on Windows vs. macOS / Linux machines.  Windows doesn't use POSIX paths, unlike macOS / Linux.  This is easy enough to change, I'll patch it.

**Comment by stewartmiles** [comment]
Fixed in https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.126

**Comment by oriontvv** [comment]
It's me again. Could you please apply the same fix for `settings` section also? Current fix doesn't solve my issue now(
And I just want to notice that there are two back-slashes on windows now - so Maybe you should escape them first.

**Comment by oriontvv** [comment]
@stewartmiles Could you please reopen the issue?

**Comment by stewartmiles** [comment]
@oriontvv ah it looks like there are some code paths in the setting dialog that leave the paths using system separators.
